const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "923048179418"
const SESSION_ID = "PRABATH-MD~nJNBnJJD#tktVOnVX1zLfG8iegKMideMZgSV556xlnTEF1ZejnY8"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
